name: sparvoll_the_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

#............PACKAGES........#
dependencies:
  flutter:
    sdk: flutter

    #....Utility Packages....#
  http: ^0.13.6
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  connectivity_plus: ^5.0.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  wakelock_plus: ^1.1.3 #Only being used in the Dummy Data Uploader to keep screen on.
  flutter_paypal_checkout: ^1.0.1


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1



  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2


    #firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.3
  flutter_facebook_auth: ^6.0.2

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/fonts/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/applep/
    - assets/icons/brands/
    - assets/Contents/
    - assets/images/reviews/



  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
